server:   
  port: 8083  
eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
spring: 
  application:
    name: springCloudGateway
  zipkin: 
    baseUrl: http://localhost:9411/
  sleuth: 
    sampler:
      percentage: 1
zuul: 
  routes: 
      hello: 
        path: /app/**
        serviceId: springcloudapp